project:
  type: website
  output-dir: docs

jupyter: python3

execute:
  warning: false
  message: false

website:
  title: ""
  site-url: 'https://blog.datakwery.com'
  site-path: '/'
  favicon: img/favicon.png
  navbar:
    background: '#213458'
    logo: img/dk_logo.png
    right:
      - text: Find Free Courses
        href: https://datakwery.com
      # - icon: github
      #   href: https://github.com/DataKwery-Founders/dk-blog
      # - about.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com/datakwery
  page-footer: 
    center: "Copyright 2024, DataKwery" 
    border: true
    background: '#213458'
format:
  html:
    theme: cosmo
    css: styles.css



